### ISSUE TITLE
On iOS 10 NSPersistentContainer actually uses the Application Support directory

### ISSUE THREAD

**Issue by malhal** [inspace-io/INSPersistentContainer#1]
On iOS 10 as of beta 2, NSPersistentContainer's defaultDirectoryURL returns the Application Support directory, creating it if necessary, and aborting if it cannot create it. e.g.
`/var/mobile/Containers/Data/Application/C708308A-5389-4EAE-96E0-840D50F6C826/Library/Application%20Support/Test2.sqlite`
This means this drop in replacement is not fully compatible because its using the Documents folder. 

Personally I was surprised to see this, given in [@numist](https://twitter.com/numist)'s talk he said it would be the Documents folder on iOS.

**Comment by m1entus** [comment]
Thanks for info, probably this could change a couple of time until we get GM, so i would have to review all new stuff and i will be working on it as soon we will get GM :)

**Comment by malhal** [comment]
Yep best to wait and see

**Comment by m1entus** [comment]
Fixed, thanks 👍

**Comment by malhal** [comment]
Great, I'll try it out and let you know if I notice anything else.

**Comment by inPhilly** [comment]
Is this still the case?
