### ISSUE TITLE
ins_dealloc to remove observers

### ISSUE THREAD

**Issue by malhal** [inspace-io/INSPersistentContainer#2]
There is a method ins_dealloc to remove the observers but the sample doesn't show how to use it, how about one of [these](http://stackoverflow.com/questions/14708905/how-do-i-access-the-dealloc-method-in-a-class-category) strategies instead?

**Comment by m1entus** [comment]
You don't need it, it is private. Just set flag to NO and will be deallocated automatically

**Comment by malhal** [comment]
I see you set them to NO in the stack class. Does Apple's implementation require that too?

**Comment by m1entus** [comment]
Apple can use NSManagedObject dealloc method to remove it, and category NO so this is small workaround for it but since iOS9 notification object are working as weak reference so nothing should happened anyway. http://useyourloaf.com/blog/unregistering-nsnotificationcenter-observers-in-ios-9/
